#!/bin/bash

echo "------------------------------------------------------------ post_push begin ---"

for tag in $(echo $DOCKER_TAG | tr "," "\n"); do
    if [ "${tag}" != "${tag/go2go/}" ]; then
        tag_date=$(date +%Y%m%d)
        new_image_name="${DOCKER_REPO}:${tag/go2go/go2go-$tag_date}"
        docker tag "${IMAGE_NAME}" "${new_image_name}"
        docker push "${new_image_name}"
    fi
done

echo "-------------------------------------------------------------- post_push end ---"
